### ISSUE TITLE
Please upload Main directory only

### ISSUE THREAD

**Issue by MugiJR** [MugiJR/smart-home-app-android#2]
Hey @Xuiao  ,
Can you please upload just the Main directory only. You can check Chaima's or My branch for reference. 
We've decided not to upload any files/folders other than Main.  

If possible, please rename your branch from master -> [Your Name]

**Comment by Xuiao** [comment]
I have modified it, please check it.
Thank you so much
















At 2022-10-16 23:15:37, "Mugesh" ***@***.***> wrote:

Hey @Xuiao ,
Can you please upload just Main directory only. You can check Chaima's or My branch for the reference.
We've decided not to upload files any files/folders others Main.

If possible, please rename your branch from master -> [Your Name]

**Comment by MugiJR** [comment]
Thanks @Xuiao 🙂
